language: csharp
mono: none
dist: xenial
dotnet: 3.1
solution: hemo-control-api/HemoControl.sln

services:
  - docker

jobs:
  include:
    - stage: sonar-scan
      script:
        - cd hemo-control-api
        - docker run -it
          --rm
          -w /app
          -v $(pwd):/app
          -e PROJECT_KEY=${PROJECT_KEY}
          -e SONAR_ORGANIZATION=${SONAR_ORGANIZATION}
          -e SONAR_URL=${SONAR_URL}
          -e SONAR_SECRET=${SONAR_SECRET}
          cassiofariasmachado/dotnet-sonarscanner:latest
          sh scripts/sonar-scan.sh