// <auto-generated />
using HemoControl.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HemoControl.Migrations
{
    [DbContext(typeof(HemoControlContext))]
    [Migration("20180203164323_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HemoControl.Entities.Infusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BleedingLocal")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date");

                    b.Property<string>("FactorBrand")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FactorLot")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("FactorUnity");

                    b.Property<bool>("IsBleeding");

                    b.Property<bool>("IsHemarthrosis");

                    b.Property<bool>("IsTreatmentContinuation");

                    b.Property<string>("TreatmentLocal")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UserId");

                    b.Property<decimal>("UserWeigth");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Infusion");
                });

            modelBuilder.Entity("HemoControl.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Weigth");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HemoControl.Entities.Infusion", b =>
                {
                    b.HasOne("HemoControl.Entities.User")
                        .WithMany("Infusions")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
