name: Hemo Control API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Build
      working-directory: hemo-control-api
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Test
      working-directory: hemo-control-api
      run: dotnet test --no-restore --verbosity normal

  sonar-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Scan
      working-directory: hemo-control-api
      env:
        PROJECT_KEY: hemo-control-api
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_URL: ${{ secrets.SONAR_URL }}
        SONAR_SECRET: ${{ secrets.SONAR_SECRET }}
      run: docker run --rm	
                      -w /app	
                      -v $(pwd):/app	
                      -e PROJECT_KEY=${PROJECT_KEY}	
                      -e SONAR_ORGANIZATION=${SONAR_ORGANIZATION}	
                      -e SONAR_URL=${SONAR_URL}	
                      -e SONAR_SECRET=${SONAR_SECRET}	
                      cassiofariasmachado/dotnet-sonarscanner:latest	
                      sh scripts/sonar-scan.sh
  
  deploy:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    needs: [build, test]

    steps:
    - uses: actions/checkout@v2

    - name: Heroku Login
      working-directory: hemo-control-api
      
      run: heroku container:login

    - name: Push image
      working-directory: hemo-control-api

      run: heroku container:push web -a hemo-control-api
    
    - name: Deploy release
      working-directory: hemo-control-api

      run: heroku container:release web -a hemo-control-api