name: Hemo Control APP

on:
  push:
    branches: [ master ]
    paths: hemo-control-app/**/*
  pull_request:
    branches: [ master ]
    paths: hemo-control-app/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Configure CI
      working-directory: hemo-control-app
      run: npm ci
    
    - name: Build
      working-directory: hemo-control-app
      run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Configure CI
      working-directory: hemo-control-app
      run: npm ci

    - name: Test
      working-directory: hemo-control-app
      run: npm test

  sonar-scan:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Configure CI
      working-directory: hemo-control-app
      run: npm ci
    
    - name: Scan
      working-directory: hemo-control-app
      env:
        PROJECT_KEY: hemo-control-app
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_URL: ${{ secrets.SONAR_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run sonar-scan
